### ISSUE TITLE
Unicode.Unihan.Radicals tests need refactoring

### ISSUE THREAD

**Issue by kipcole9** [elixir-unicode/unicode_unihan#3]
Now that `Unicode.Unihan.Radical.radicals/0` returns a map of traditional and simplied entries the function `radical/2` needs reworking. One option is to require another argument (`:Hant` or `:Hans`).

**Comment by jkwchui** [comment]
These have been resolved in this [Commit](https://github.com/elixir-unicode/unicode_unihan/commit/8dfaa4c26e3b7bbd2c6a72a73b5bdd18a0bcc683)
