### ISSUE TITLE
Add Mix.install([:unicode_unihan]) to the livebooks

### ISSUE THREAD

**Issue by kipcole9** [elixir-unicode/unicode_unihan#4]
I believe the livebooks should start with installation of the library. For example:
```elixir
Mix.install([:unicode_unihan])
```
Otherwise there is no library available unless you jump into a running session. My observation is that the `Mix.install` approach is now the most idiomatic and common pattern for livebooks.

**Comment by jkwchui** [comment]
done in latest commit.

**Comment by kipcole9** [comment]
🥳🥳🥳🥳🥳 Looking really good.  I really need to do a lot more Livebook work on my libs!
